"""add google oauth fields

Revision ID: 3921f137e4ca
Revises: 51b4143a8596
Create Date: 2026-08-08 07:00:33.307066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3921f137e4ca'
down_revision: Union[str, Sequence[str], None] = '51b4143a8596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'auth_provider',
            sa.String(length=20),
            nullable=False,
            server_default='local'
    )
)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(
        "uq_users_google_id",
        "users",
        ["google_id"]
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_users_google_id",
        "users",
        type_="unique"
)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
