"""add resume analysis job status

Revision ID: ad5185b8a64f
Revises: 639966e9554b
Create Date: 2026-08-11 15:50:47.821631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad5185b8a64f'
down_revision: Union[str, Sequence[str], None] = '639966e9554b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_analyses_id'), table_name='resume_analyses')
    op.drop_index(op.f('ix_resume_analyses_resume_id'), table_name='resume_analyses')
    op.drop_index(op.f('ix_resume_analyses_user_id'), table_name='resume_analyses')
    op.drop_table('resume_analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_description_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jd_profile_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('analysis_result_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('resume_analyses_resume_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('resume_analyses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resume_analyses_pkey'))
    )
    op.create_index(op.f('ix_resume_analyses_user_id'), 'resume_analyses', ['user_id'], unique=False)
    op.create_index(op.f('ix_resume_analyses_resume_id'), 'resume_analyses', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_analyses_id'), 'resume_analyses', ['id'], unique=False)
    # ### end Alembic commands ###
